const images = [
  { Id: 1, name: "Canada", source: require("../assets/images/Flags/canada.png") },
  { Id: 2, name: "USA", source: require("../assets/images/Flags/usa.png") },
  { Id: 3, name: "Mexico", source: require("../assets/images/Flags/mexico.png") },
  { Id: 4, name: "El Salvador", source: require("../assets/images/Flags/elsalvador.png") },
  { Id: 5, name: "Colombia", source: require("../assets/images/Flags/colombia.png") },
  { Id: 6, name: "Venezuela", source: require("../assets/images/Flags/venezuela.png") },
  { Id: 7, name: "Brazil", source: require("../assets/images/Flags/brazil.png") },
  { Id: 8, name: "Peru", source: require("../assets/images/Flags/peru.png") },
  { Id: 9, name: "Bolivia", source: require("../assets/images/Flags/bolivia.png") },
  { Id: 10, name: "Paraguay", source: require("../assets/images/Flags/paraguay.png") },
  { Id: 11, name: "Argentina", source: require("../assets/images/Flags/argentina.png") },
  { Id: 12, name: "Chile", source: require("../assets/images/Flags/chile.png") },
  { Id: 13, name: "Uruguay", source: require("../assets/images/Flags/uruguay.png") },
  { Id: 14, name: "Cuba", source: require("../assets/images/Flags/cuba.png") },
  { Id: 15, name: "Greenland", source: require("../assets/images/Flags/greenland.png") },
  { Id: 16, name: "Iceland", source: require("../assets/images/Flags/iceland.png") },
  { Id: 17, name: "South Africa", source: require("../assets/images/Flags/southafrica.png") },
  { Id: 18, name: "Namibia", source: require("../assets/images/Flags/namibia.png") },
  { Id: 19, name: "Botswana", source: require("../assets/images/Flags/botswana.png") },
  { Id: 20, name: "Zimbabwe", source: require("../assets/images/Flags/zimbabwe.png") },
  { Id: 21, name: "Mozambique", source: require("../assets/images/Flags/mozambique.png") },
  { Id: 22, name: "Zambia", source: require("../assets/images/Flags/zambia.png") },
  { Id: 23, name: "Angola", source: require("../assets/images/Flags/angola.png") },
  { Id: 24, name: "Congo", source: require("../assets/images/Flags/democraticrepublicofcongo.png") },
  { Id: 25, name: "Cameroon", source: require("../assets/images/Flags/cameroon.png") },
  { Id: 26, name: "Central African Republic", source: require("../assets/images/Flags/centralafricanrepublic.png") },
  { Id: 27, name: "Tanzania", source: require("../assets/images/Flags/tanzania.png") },
  { Id: 28, name: "Kenya", source: require("../assets/images/Flags/kenya.png") },
  { Id: 29, name: "Somalia", source: require("../assets/images/Flags/somalia.png") },
  { Id: 30, name: "Ethiopia", source: require("../assets/images/Flags/ethiopia.png") },
  { Id: 31, name: "Sudan", source: require("../assets/images/Flags/sudan.png") },
  { Id: 32, name: "Egypt", source: require("../assets/images/Flags/egypt.png") },
  { Id: 33, name: "Libya", source: require("../assets/images/Flags/libya.png") },
  { Id: 34, name: "Algeria", source: require("../assets/images/Flags/algeria.png") },
  { Id: 35, name: "Mauritania", source: require("../assets/images/Flags/mauritania.png") },
  { Id: 36, name: "Mali", source: require("../assets/images/Flags/mali.png") },
  { Id: 37, name: "Madagascar", source: require("../assets/images/Flags/madagascar.png") },
  { Id: 38, name: "Spain", source: require("../assets/images/Flags/spain.png") },
  { Id: 39, name: "France", source: require("../assets/images/Flags/france.png") },
  { Id: 40, name: "Ireland", source: require("../assets/images/Flags/ireland.png") },
  { Id: 41, name: "Germany", source: require("../assets/images/Flags/germany.png") },
  { Id: 42, name: "Italy", source: require("../assets/images/Flags/italy.png") },
  { Id: 43, name: "Malta", source: require("../assets/images/Flags/malta.png") },
  { Id: 44, name: "Austria", source: require("../assets/images/Flags/austria.png") },
  { Id: 45, name: "Serbia", source: require("../assets/images/Flags/serbia.png") },
  { Id: 46, name: "Hellas", source: require("../assets/images/Flags/hellas.png") },
  { Id: 47, name: "England", source: require("../assets/images/Flags/england.png") },
  { Id: 48, name: "Scandinavia", source: require("../assets/images/Flags/scandinavia.png") },
  { Id: 49, name: "Poland", source: require("../assets/images/Flags/poland.png") },
  { Id: 50, name: "Ukraine", source: require("../assets/images/Flags/ukraine.png") },
  { Id: 51, name: "Russia", source: require("../assets/images/Flags/russia.png") },
  { Id: 52, name: "China", source: require("../assets/images/Flags/china.png") },
  { Id: 53, name: "North Korea", source: require("../assets/images/Flags/northkorea.png") },
  { Id: 54, name: "South Korea", source: require("../assets/images/Flags/southkorea.png") },
  { Id: 55, name: "Japan", source: require("../assets/images/Flags/japan.png") },
  { Id: 56, name: "Turkey", source: require("../assets/images/Flags/turkey.png") },
  { Id: 57, name: "Jordan", source: require("../assets/images/Flags/jordan.png") },
  { Id: 58, name: "Israel", source: require("../assets/images/Flags/israel.png") },
  { Id: 59, name: "Iraq", source: require("../assets/images/Flags/iraq.png") },
  { Id: 60, name: "Iran", source: require("../assets/images/Flags/iran.png") },
  { Id: 61, name: "Armenia", source: require("../assets/images/Flags/armenia.png") },
  { Id: 62, name: "Turkmenistan", source: require("../assets/images/Flags/turkmenistan.png") },
  { Id: 63, name: "Afghanistan", source: require("../assets/images/Flags/afghanistan.png") },
  { Id: 64, name: "India", source: require("../assets/images/Flags/india.png") },
  { Id: 65, name: "Laos", source: require("../assets/images/Flags/laos.png") },
  { Id: 66, name: "Sri Lanka", source: require("../assets/images/Flags/srilanka.png") },
  { Id: 67, name: "Taiwan", source: require("../assets/images/Flags/taiwan.png") },
  { Id: 68, name: "Saudi Arabia", source: require("../assets/images/Flags/saudiarabia.png") },
  { Id: 69, name: "Australia", source: require("../assets/images/Flags/australia.png") },
  { Id: 70, name: "Tasmania", source: require("../assets/images/Flags/tasmania.png") },
  { Id: 71, name: "New Zealand", source: require("../assets/images/Flags/newzealand.png") },
  { Id: 72, name: "United Arab Emirates", source: require("../assets/images/Flags/unitedarabemirates.png") },
  { Id: 73, name: "Indonesia", source: require("../assets/images/Flags/indonesia.png") },
  { Id: 74, name: "Philippines", source: require("../assets/images/Flags/philippines.png") },
];

export default images;
